export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_LIST_PRODUCT = 'SET_LIST_PRODUCT';
export const SET_LIST_AREA = 'SET_LIST_AREA';
export const SET_LIST_BLOCK = 'SET_LIST_BLOCK';
